apiVersion: skaffold/v1
kind: Config
metadata:
  name: spring-boot-microservice
build:
  artifacts:
  - image: kaji80docker/micro-service
deploy:
  helm:
    releases:
    - name: micro-service-devops
      chartPath: micro-service
      values:
        image: kaji80docker/micro-service

